[workspace]
members = [
    "emulator",
    "emulator/common",
    "emulator/gba",

    "libs/graphics",
    "libs/sound",
    "libs/windowing",
]

[profile.dev]
# We want the dev profile to run really well (cause emulators) but still be debuggable
opt-level = 3
debug = 2
